name: Slack

on: push
  branches: 
    - main
  paths: 
    - "REEDME.md"

jobs: 
  slack:
    run-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env: 
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Github Actions Slack Notification
